#!/bin/bash

BASE_DIR=$SHARED_DIRECTORY
PREFIX=$GROUP_PREFIX
not_corrected=0
corrected=0
dontneed=0

#for DIR in $(ls -l $BASE_DIR | awk '{if ($4 == "root"){print $9;}}'); do
for DIR in $(ls $BASE_DIR); do
	if (cd $BASE_DIR && getfacl $DIR | grep -i $PREFIX$DIR >/dev/null 2>&1 ); then
		(( dontneed++ ))
	else		
		echo -n "CRON: Directory "$DIR" not setted. Checking group "$PREFIX$DIR" existence..."
		if /usr/bin/getent group $PREFIX$DIR > /dev/null; then 
			echo "OK" 				
			echo -n "CRON      Adjusting group on directory "$BASE_DIR"/"$DIR"..."
			if ( chmod 0070 $BASE_DIR/$DIR && \
			     setfacl -b $BASE_DIR/$DIR && \
			     setfacl -m user::--- $BASE_DIR/$DIR && \
		     	     setfacl -m group::rwx $BASE_DIR/$DIR && \		     	     
		     	     setfacl -m group:$PREFIX$DIR:rwx $BASE_DIR/$DIR && \
		     	     setfacl -m other::--- $BASE_DIR/$DIR && \			     
			     setfacl -m default:group:$PREFIX$DIR:rwx $BASE_DIR/$DIR && \
			     setfacl -m default:user::rwx $BASE_DIR/$DIR );
			     setfacl -m default:group::rwx $BASE_DIR/$DIR );
			     setfacl -m default:other::r-x $BASE_DIR/$DIR );
			then			   
				echo "OK"
				(( corrected++ )) 
				/etc/cron.daily/userlinks $DIR
			else
				(( not_corrected++ )) 
				echo "FAILED" 
			fi		

		else
			echo "NOT FOUND"
	       		(( not_corrected++ )) 
		fi
	fi
done

echo "CRON: ***************************************************************"
echo "CRON: Directories adjusted: "$corrected
echo "CRON: ***************************************************************"
echo "CRON: Directories needing adjustment: "$not_corrected
echo "CRON: ***************************************************************"
echo "CRON: Directories already adjusted: "$dontneed
echo "CRON: ***************************************************************"
